---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo cache (RedHat)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

  - name: updates repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFG71FCnnl79+D4Y1KspNX1fvGqBrukhr2txVQhjEE9D admin"



- hosts: web_server
  become: true
  tasks:

  - name: install apache and php on ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php on Redhat servers
    tags: apache,redhat,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"
  
  - name: start httpd (RedHat)
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: copy default html file for site
    tags: apache,redhat,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "RedHat"
    register: httpd

  - name: reatart httpd (Redhat)
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed


- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package ( RedHat )
    tags: db,mariadb,redhat
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"


  - name: install mariadb package ( Ubuntu )
    tags: db,mariadb,ubuntu 
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest  


